
quarkus.banner.enabled=false
quarkus.analytics.disabled=true

# Allow reflective access to java.lang for JBoss Threads on Java 24+
quarkus.jvm.args=--add-opens java.base/java.lang=ALL-UNNAMED

# quarkus.log.console.stderr=true
# quarkus.log.console.stdout=false

# quarkus.package.jar.add-runner-suffix=false

quarkus.log.category."io.quarkus".level=OFF

# quarkus.native.compression.level=10
# quarkus.native.compression.additional-args=--ultra-brute,-v

# quarkus.native.binary.name=exterminate

quarkus.datasource.exterminate.db-kind=h2
quarkus.datasource.exterminate.username=username
quarkus.datasource.exterminate.jdbc.url=jdbc:h2:${user.home}/.exterminate/h2/exterminate
quarkus.datasource.exterminate.jdbc.max-size=12

# quarkus.hibernate-orm."exterminate".packages=ay.dev.entity
# quarkus.hibernate-orm."exterminate".datasource=exterminate
# quarkus.hibernate-orm."exterminate".database.generation=update

# Log everything to a file and disable console logging
quarkus.log.file.enable=true
quarkus.log.file.path=${user.home}/.exterminate/log/exterminate.log
quarkus.log.file.rotation.max-file-size=10M
quarkus.log.file.rotation.max-backup-index=5
quarkus.log.console.enable=false

