quarkus.log.category."io.quarkus".level=INFO

quarkus.datasource."exterminate".db-kind=h2
quarkus.datasource."exterminate".username=username
quarkus.datasource."exterminate".jdbc.url=jdbc:h2:${user.home}/.exterminate/h2-dev/exterminate

# let hibernate update schema
quarkus.hibernate-orm.database.generation=update

# Sample seekExclude configuration for ExterminateConfig
seek.exclude.all-regions.provider=aws
seek.exclude.all-regions.service=ec2
seek.exclude.all-regions.resourceType=region
seek.exclude.all-regions.region=*

seek.include.allow-virginia.provider=aws
seek.include.allow-virginia.service=ec2
seek.include.allow-virginia.resourceType=region
seek.include.allow-virginia.region=us-east-1

